export const PAGE_MAX_WIDTH = 1200;

export const BOOK_ITEM_WIDTH = 285;

export const BOOK_ITEM_WIDTH_MOBILE = 182;

export const BOOK_ITEM_HEIGHT = BOOK_ITEM_WIDTH;

export const BOOK_ITEM_HORIZON_WIDTH = 100;

export const BOOK_ITEM_HORIZON_HEIGHT = BOOK_ITEM_HORIZON_WIDTH * 1.4;
